# Topics and Privileges Configuration

topics:
  monterra.event:
    topic: "monterra.event"
    read_roles: ["ext_reader", "int_reader"]
    write_roles: ["ext_writer", "int_writer"]
    description: "Monterra events topic"
  
  pact_update.event:
    topic: "pact_update.event"
    read_roles: ["ext_reader", "int_reader"]
    write_roles: ["ext_writer", "int_writer"]
    description: "Pact update events topic"

roles:
  ext_reader:
    name: "ext_reader"
    description: "EXT network message reader"
    topics: ["monterra.event", "pact_update.event"]
  
  ext_writer:
    name: "ext_writer"
    description: "EXT network message writer"
    topics: ["monterra.event", "pact_update.event"]
  
  int_reader:
    name: "int_reader"
    description: "INT network message reader"
    topics: ["monterra.event", "pact_update.event"]
  
  int_writer:
    name: "int_writer"
    description: "INT network message writer"
    topics: ["monterra.event", "pact_update.event"]